name = "vmail"
main = "worker/src/index.ts"

# 打包配置
minify = true
compatibility_flags = [ "nodejs_compat" ]
compatibility_date = "2025-03-01"
keep_vars = true

# 启用 D1 数据库
[[d1_databases]]
binding = "DB"
database_name = "${D1_DATABASE_NAME}"
database_id = "${D1_DATABASE_ID}"

# feat: 添加 D1 迁移配置
# 这个配置告诉 wrangler 在部署时自动运行 `./drizzle` 目录下的迁移文件
[[migrations]]
tag = "v1" # 迁移的唯一标识符
new_classes = ["D1_ERROR"] # 迁移相关的错误类
# 将迁移应用到名为 "DB" 的 D1 数据库绑定
binding = "DB"
# 指定迁移文件所在的目录
migrations_dir = "drizzle"


# 定义环境变量和密钥
[vars]
EMAIL_DOMAIN = "${EMAIL_DOMAIN}"
TURNSTILE_KEY = "${TURNSTILE_KEY}"
COOKIES_SECRET = "${COOKIES_SECRET}"
TURNSTILE_SECRET = "${TURNSTILE_SECRET}"

# 配置邮件处理
[triggers]
crons = ["0 * * * *"] # 每小时运行一次清理任务

# 构建配置
[build]
command = "pnpm run build"

# 静态资源配置
[assets]
binding = "ASSETS"
directory = "frontend/build/client"